using NextGen.Modules.Parties.RestockSubscriptions.Dtos;

namespace NextGen.Modules.Parties.RestockSubscriptions.Features.GettingRestockSubscriptionById;

public record GetRestockSubscriptionByIdResponse(RestockSubscriptionDto RestockSubscription);
